server:
  port: 8091
spring:
  application:
    name: sca-consumer
  cloud:
    nacos:
      discovery:
        access-key: localhost:8848
    sentinel:
      transport:
        port: 8099 #跟sentinel控制台交流的端口,随意指定一个未使用的端口即可
        dashboard: localhost:8180 # 指定sentinel控制台地址。
      eager: true
feign:
  hystrix:
    enabled: true
